### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by lidel** [ipfs/go-pinning-service-http-client#14]
Panic with go-ipfs 0.12 while doing `ipfs pin remote ls --service=estuary --status=queued`

```
Daemon is ready
panic: runtime error: index out of range [-1]

goroutine 113809296 [running]:
github.com/ipfs/go-pinning-service-http-client.(*Client).Ls.func1(0xc0bceda900, 0xc0bceda8a0, 0xc051651d58, 0x264b078, 0xc070f03b00, 0xc0bceda960)
	github.com/ipfs/go-pinning-service-http-client@v0.1.0/client.go:179 +0x509
created by github.com/ipfs/go-pinning-service-http-client.(*Client).Ls
	github.com/ipfs/go-pinning-service-http-client@v0.1.0/client.go:154 +0x1b5
```
Seems that: 
https://github.com/ipfs/go-pinning-service-http-client/blob/133fb5347ddc144063d2e7e88e8c37ed8f8fd60c/client.go#L179

fails super hard because of missing results:

```console
$ curl  -H "Authorization: Bearer [secret]" "https://api.estuary.tech/pinning/pins?status=queued"
{"count":15,"results":null}
```

**Comment by lidel** [comment]
@aschmahmann I suspect this is only a symptom of deeper risk space (other edge cases when pinning service does not comply to the OpenAPI spec). Panic in this client should not bring the daemon down, but only fail specific command.

Are we able to wrap the  go-pinning-service-http-client in the same panic recovery we have in other places in go-ipfs? I'm game to do the PRs, just point me at existing recovery code so i don't reinvent the wheel.

**Comment by lidel** [comment]
Seems like something we need to fix in the spec itself: 

> OpenAPI 3.0 does not have an explicit null type as in JSON Schema, but you can use nullable: true to specify that the value may be null. 
> – https://swagger.io/docs/specification/data-models/data-types/#null

Filled https://github.com/ipfs/pinning-services-api-spec/issues/89

**Comment by guseggert** [comment]
I agree we need to gracefully handle this client-side (at least test the length of the slice before indexing on it), but is this also a server bug? Shouldn't the response have 15 results?

**Comment by lidel** [comment]
Yes, estuary's server-side bug was fixed in https://github.com/application-research/estuary/pull/126 
but the question aropund nulls remains – we need to update OpenAPI spec to be more liberal, and see if that solves the problem https://github.com/ipfs/pinning-services-api-spec/issues/89#issuecomment-1093313304

**Comment by guseggert** [comment]
It's unclear to me how allowing null results in the spec would have helped here? Wouldn't the slice still have been nil in that case and this panic would have still occurred?

**Comment by lidel** [comment]
@guseggert in spare moment take a look at proposed fix in https://github.com/ipfs/go-pinning-service-http-client/pull/18 :pray:
